# Generated by Django 5.0.3 on 2024-03-28 13:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=50)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superadmin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('soil_quality', models.CharField(max_length=50)),
                ('pest_control', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='farm_documents/')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(default='default.png', upload_to='customer/%Y/%m/%d/')),
                ('city', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('blood_group', models.CharField(max_length=50, null=True)),
                ('date_joined', models.DateTimeField(blank=True, default=datetime.date.today)),
                ('date_of_birth', models.DateField(null=True)),
                ('age_years', models.PositiveIntegerField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='farming_app.account')),
            ],
        ),
        migrations.CreateModel(
            name='DailyUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('document', models.FileField(blank=True, null=True, upload_to='daily_update_documents/')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farming_app.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('crop_type', models.CharField(max_length=100)),
                ('planting_date', models.DateTimeField()),
                ('harvest_date', models.DateTimeField()),
                ('document', models.FileField(blank=True, null=True, upload_to='crop_documents/')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farming_app.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('nitrogen_content', models.FloatField()),
                ('phosphorus_content', models.FloatField()),
                ('potassium_content', models.FloatField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farming_app.farm')),
                ('recommended_for_crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farming_app.crop')),
            ],
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_date', models.DateField()),
                ('yield_amount', models.FloatField()),
                ('document', models.FileField(blank=True, null=True, upload_to='harvest_documents/')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farming_app.crop')),
            ],
        ),
        migrations.CreateModel(
            name='Soil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('texture', models.CharField(blank=True, max_length=100, null=True)),
                ('pH_level', models.FloatField(blank=True, null=True)),
                ('organic_matter', models.FloatField(blank=True, null=True)),
                ('moisture_retention', models.FloatField(blank=True, null=True)),
                ('drainage_capacity', models.FloatField(blank=True, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farming_app.farm')),
            ],
        ),
        migrations.AddField(
            model_name='farm',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farming_app.userprofile'),
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('document', models.FileField(blank=True, null=True, upload_to='weather_data_documents/')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farming_app.farm')),
            ],
        ),
    ]
